version: '3'
services:
  code-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - PASSWORD=password
    volumes:
      - ./_volumes/:/home/coder/
